export const WS_CONNECTION_START = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS = "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED = "WS_CONNECTION_CLOSED";
export const WS_GET_ORDERS = "WS_GET_ORDERS";
export const WS_PROFILE_CONNECTION_START = "WS_AUTH_CONNECTION_START";
export const WS_PROFILE_CONNECTION_SUCCESS = "WS_AUTH_CONNECTION_SUCCESS";
export const WS_PROFILE_CONNECTION_ERROR = "WS_AUTH_CONNECTION_ERROR";
export const WS_PROFILE_CONNECTION_CLOSED = "WS_AUTH_CONNECTION_CLOSED";
export const WS_GET_PROFILE_ORDERS = "WS_GET_AUTH_ORDERS";

export const wsActions = {
  wsInit: WS_CONNECTION_START,
  onOpen: WS_CONNECTION_SUCCESS,
  onClose: WS_CONNECTION_CLOSED,
  onError: WS_CONNECTION_ERROR,
  onMessage: WS_GET_ORDERS,
};

export const wsProfileActions = {
  wsInit: WS_PROFILE_CONNECTION_START,
  onOpen: WS_PROFILE_CONNECTION_SUCCESS,
  onClose: WS_PROFILE_CONNECTION_CLOSED,
  onError: WS_PROFILE_CONNECTION_ERROR,
  onMessage: WS_GET_PROFILE_ORDERS,
};